# This is the display information
# The title is what will be shown above the physical drop
# The dropped item will look like the display item
# Use items from: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# Use sounds from: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# Set pickup_sound to none for no sound to play on pickup
display:
  shard:
    title: '&A&L%amt% Shard(s)'
    item: PRISMARINE_SHARD
    pickup_sound: ENTITY_PLAYER_LEVELUP
  soul:
    title: '&C&L%amt% Soul Crystal(s)'
    item: NETHER_STAR
    pickup_sound: ENTITY_PLAYER_LEVELUP

# This is the amount of time (in seconds) the drop will only be able to be picked up by the player who broke the block
safe_period: 2

# These are the messages that are sent upon pickup. use %amt% for the amounts
messages:
  soul: '&7&L>> You picked up &C&L%amt% Souls'
  shard: '&7&L>> You picked up &A&L%amt% Shards'

# Enter the information for the soul crystal here
soul:
  item:
    name: '&C&LSoul Crystal'
    type: NETHER_STAR
    lore:
      - '&7This is used for enchanting'

# These are the chances (as a percentage) and the amounts (in a range from min-max)
# for drops for each type of block. Please use valid block types from the materials list above
drops:
  STONE:
    soul:
      chance: 50
      min: 1
      max: 3
    shard:
      chance: 50
      min: 1
      max: 3