name: AiridaleDrops
author: Vhbob
version: 1.1.0
description: A shards and souls drops plugin for AiridaleMC
main: me.vhbob.airidaledrops.AiridaleDrops
api-version: 1.16
depend:
  - TokenManager
commands:
  SetSoul:
    description: Set the soul drop item to the item in your hand
    permission: drops.soul.set
    permission-message: '§CYou do not have permission to do that!'
    usage: '§CEnsure you have an item in your hand!'